# Generated by Django 2.2 on 2019-05-27 18:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import kerckhoff.integrations.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0003_package_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "integration_type",
                    models.CharField(choices=[("wpc", "Wordpress.com")], max_length=3),
                ),
                (
                    "_auth_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=kerckhoff.integrations.models.AuthData.empty
                    ),
                ),
                (
                    "params",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.PackageSet",
                    ),
                ),
            ],
        )
    ]
