# Generated by Django 2.1.5 on 2019-01-30 05:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64)),
                ('drive_folder_id', models.CharField(max_length=512)),
                ('drive_folder_url', models.URLField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('processing', models.BooleanField(default=False)),
                ('cached_article_preview', models.TextField(blank=True)),
                ('publish_date', models.DateField()),
                ('last_fetched_date', models.DateTimeField(blank=True, null=True)),
                ('_content_type', models.CharField(blank=True, choices=[('PT', 'Plaintext'), ('HL', 'HTML')], default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=512)),
                ('drive_folder_url', models.URLField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_description', models.TextField(blank=True)),
                ('article_data', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.Package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.PackageVersion'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.PackageSet'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('package_set', 'slug')},
        ),
    ]
