# Generated by Django 2.2 on 2019-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("packages", "0002_auto_20190526_2006")]

    operations = [
        migrations.AddField(
            model_name="package",
            name="state",
            field=models.CharField(
                choices=[
                    ("pub", "Published"),
                    ("rdy", "Ready"),
                    ("wip", "In Progress"),
                ],
                default="wip",
                max_length=3,
            ),
        )
    ]
