# Generated by Django 2.2 on 2020-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wp_id', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordpressCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wp_id', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
            ],
        ),
    ]
