version: "2"

services:
  postgres:
    image: postgres:9.6
  web:
    restart: always
    env_file:
      - .env
      - .secrets
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  redis:
    image: redis:5-alpine
  # documentation:
  #   restart: always
  #   build: ./
  #   command: "mkdocs serve"
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "8001:8001"
