# Generated by Django 2.1.5 on 2019-04-30 01:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
