# Generated by Django 2.1.5 on 2019-01-30 03:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, default='Contributor', max_length=100)),
                ('profile_img', models.ImageField(null=True, upload_to='profile/imgs/')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('auth_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('role', models.CharField(choices=[('CT', 'Contributor'), ('ED', 'Editor'), ('AD', 'Admin')], max_length=2)),
            ],
        ),
    ]
