TEXT = "txt"
AML = "aml"
IMAGE = "img"
MARKDOWN = "mdn"
SPREADSHEET = "xls"

DTYPE_CHOICES = (
    (TEXT, "TEXT"),
    (AML, "ARCHIEML"),
    (IMAGE, "IMAGE"),
    (MARKDOWN, "MARKDOWN"),
    (SPREADSHEET, "SPREADSHEET"),
)

SUPPORTED_ITEM_TYPES = (TEXT, AML, IMAGE, MARKDOWN, SPREADSHEET)
