authors = [
    {
        "id": 4785,
        "extra_ids": [4832],
        "name": "Aalhad Patankar",
        "slug": "camayak_32",
    },
    {
        "id": 6302,
        "name": "Aali Akmal",
        "slug": "aali-akmal",
    },
    {
        "id": 5758,
        "name": "Aaron Boudaie",
        "slug": "aaron-boudaie",
    },
    {
        "id": 5576,
        "name": "Aaron Julian",
        "slug": "aaron-julian",
    },
    {
        "id": 5671,
        "extra_ids": [6384],
        "name": "Aaron Lerner",
        "slug": "aaron-lerner",
    },
    {
        "id": 6399,
        "name": "Alyssa Wheeler",
        "slug": "alyssa-wheeler",
    },
    {
        "id": 4064,
        "name": "Basheer Alas",
        "slug": "basheer_alas",
    },
    {
        "id": 924,
        "name": "Dan Sheehan",
        "slug": "dan_sheehan",
    },
    {
        "id": 4721,
        "extra_ids": [4849],
        "name": "Hee Jae Choi",
        "slug": "hchoi",
    },
    {
        "id": 177,
        "name": "Abigail Palmer",
        "slug": "abigail_palmer",
    },
    {
        "id": 182,
        "name": "Alex Palmer",
        "slug": "alex_palmer",
    },
    {
        "id": 4214,
        "name": "Annika Hammerschlag",
        "slug": "annika_hammerschlag",
    },
    {
        "id": 910,
        "name": "Blaise Hammer",
        "slug": "blaise_hammer",
    },
    {
        "id": 5656,
        "name": "Cameron Patterson",
        "slug": "cameron-patterson",
    },
    {
        "id": 5850,
        "name": "Cameron Vernali",
        "slug": "cameron-vernali",
    },
    {
        "id": 6376,
        "name": "Catherine Montgomery",
        "slug": "catherine-montgomery",
    },
    {
        "id": 6202,
        "name": "Dominik Stemer",
        "slug": "dominik-stemer",
    },
    {
        "id": 5929,
        "name": "Emily Merz",
        "slug": "emily-merz",
    },
    {
        "id": 5961,
        "name": "Esmeralda Lopez",
        "slug": "elopez",
    },
]

categories = [
    {
        "id": 1425,
        "count": 820,
        "description": "",
        "link": "http://165.227.25.233/category/news/a-closer-look/",
        "name": "A Closer Look",
        "slug": "a-closer-look",
        "taxonomy": "category",
        "parent": 1424,
    },
    {
        "id": 6044,
        "count": 37,
        "description": "",
        "link": "http://165.227.25.233/category/quad/ae/",
        "name": "A&amp;E",
        "slug": "ae",
        "taxonomy": "category",
        "parent": 12848,
    },
    {
        "id": 5213,
        "count": 224,
        "description": "",
        "link": "http://165.227.25.233/category/spectrum/ae-spectrum/",
        "name": "A&amp;E Spectrum",
        "slug": "ae-spectrum",
        "taxonomy": "category",
        "parent": 5204,
    },
    {
        "id": 16717,
        "count": 30,
        "description": "",
        "link": "http://165.227.25.233/category/quad/academics/",
        "name": "Academics",
        "slug": "academics",
        "taxonomy": "category",
        "parent": 12848,
    },
    {
        "id": 22178,
        "count": 0,
        "description": "",
        "link": "http://165.227.25.233/category/pizza/sauce/alfredo/",
        "name": "Alfredo",
        "slug": "alfredo",
        "taxonomy": "category",
        "parent": 22165,
    },
    {
        "id": 1454,
        "count": 14620,
        "description": "",
        "link": "http://165.227.25.233/category/arts-entertainment/",
        "name": "Arts",
        "slug": "arts-entertainment",
        "taxonomy": "category",
        "parent": 0,
    },
    {
        "id": 1455,
        "count": 824,
        "description": "",
        "link": "http://165.227.25.233/category/arts-entertainment/ae-columns/",
        "name": "Arts Columns",
        "slug": "ae-columns",
        "taxonomy": "category",
        "parent": 1454,
    },
    {
        "id": 21976,
        "count": 42,
        "description": "",
        "link": "http://165.227.25.233/category/sports/athletics-news/",
        "name": "Athletics News",
        "slug": "athletics-news",
        "taxonomy": "category",
        "parent": 1431,
    },
    {
        "id": 22177,
        "count": 0,
        "description": "",
        "link": "http://165.227.25.233/category/pizza/sauce/barbecue/",
        "name": "Barbecue",
        "slug": "barbecue",
        "taxonomy": "category",
        "parent": 22165,
    },
    {
        "id": 1432,
        "count": 804,
        "description": "",
        "link": "http://165.227.25.233/category/sports/baseball/",
        "name": "Baseball",
        "slug": "baseball",
        "taxonomy": "category",
        "parent": 1431,
    },
    {
        "id": 14070,
        "count": 81,
        "description": "",
        "link": "http://165.227.25.233/category/graphics/",
        "name": "Graphics",
        "slug": "graphics",
        "taxonomy": "category",
        "parent": 0,
    },
    {
        "id": 1436,
        "count": 415,
        "description": "",
        "link": "http://165.227.25.233/category/sports/gymnastics/",
        "name": "Gymnastics",
        "slug": "gymnastics",
        "taxonomy": "category",
        "parent": 1431,
    },
    {
        "id": 12329,
        "count": 62,
        "description": "",
        "link": "http://165.227.25.233/category/interactive-page/",
        "name": "Interactive Page",
        "slug": "interactive-page",
        "taxonomy": "category",
        "parent": 0,
    },
    {
        "id": 1438,
        "count": 203,
        "description": "",
        "link": "http://165.227.25.233/category/sports/mens-golf/",
        "name": "Men's Golf",
        "slug": "mens-golf",
        "taxonomy": "category",
        "parent": 1431,
    },
    {
        "id": 1467,
        "count": 370,
        "description": "",
        "link": "http://165.227.25.233/category/photo-galleries/",
        "name": "Photo Archives",
        "slug": "photo-galleries",
        "taxonomy": "category",
        "parent": 0,
    },
    {
        "id": 1444,
        "count": 85,
        "description": "",
        "link": "http://165.227.25.233/category/sports/rowing/",
        "name": "Rowing",
        "slug": "rowing",
        "taxonomy": "category",
        "parent": 1431,
    },
    {
        "id": 1429,
        "count": 1181,
        "description": "",
        "link": "http://165.227.25.233/category/news/student-government/",
        "name": "Student Government",
        "slug": "student-government",
        "taxonomy": "category",
        "parent": 1424,
    },
    {
        "id": 22166,
        "count": 0,
        "description": "",
        "link": "http://165.227.25.233/category/pizza/toppings/",
        "name": "Toppings",
        "slug": "toppings",
        "taxonomy": "category",
        "parent": 22163,
    },
    {
        "id": 1,
        "count": 1922,
        "description": "",
        "link": "http://165.227.25.233/category/uncategorized/",
        "name": "Uncategorized",
        "slug": "uncategorized",
        "taxonomy": "category",
        "parent": 0,
    },
    {
        "id": 1448,
        "count": 193,
        "description": "",
        "link": "http://165.227.25.233/category/sports/womens-golf/",
        "name": "Women's Golf",
        "slug": "womens-golf",
        "taxonomy": "category",
        "parent": 1431,
    }
]
